# 实验2：数据分析处理库Pandas的使

### 1.导入 Pandas 库并简写为 pd

In [1]:
import pandas as pd

### 2. 从列表arr = [0, 1, 2, 3, 4]创建 Series

In [2]:
arr = [0, 1, 2, 3, 4]
df2 = pd.Series(arr) # 如果不指定索引，则默认从 0 开始
df2

0    0
1    1
2    2
3    3
4    4
dtype: int64

### 3. 从字典d = {'a':1,'b':2,'c':3,'d':4,'e':5}创建 Series

In [3]:
d = {'a':1,'b':2,'c':3,'d':4,'e':5}
df3 = pd.Series(d)
df3

a    1
b    2
c    3
d    4
e    5
dtype: int64

### 4. 从 NumPy 数组num_arr = np.random.randn(6, 4)创建 DataFrame，列名['A', 'B', 'C', 'D']，行索引为默认

In [4]:
import numpy as np
num_arr = np.random.randn(6, 4)  # 传入 numpy 随机数组
columns = ['A', 'B', 'C', 'D']
df4 = pd.DataFrame(num_arr,  columns=columns)
df4

          A         B         C         D
0  1.168500  0.497461  0.781373 -0.304634
1 -0.069058 -0.703679 -0.297804  0.473984
2 -0.512891  1.025739  2.135949  0.443888
3 -1.304791  2.408792 -1.009998 -0.898365
4  0.624341 -0.536354  1.350728 -1.314161
5  1.758720 -0.532177 -0.236829  0.218248

### 5. 定义df：从字典对象创建DataFrame，并设置索引

In [5]:
import numpy as np
data = {
    'animal':
    ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority':
    ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data, index=labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 5.1 展示df的前3行

In [6]:
df.iloc[:3]
# 方法二
#df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 5.2 取出df的animal和age列

In [7]:
df.loc[:, ['animal', 'age']]
# 方法二
# df[['animal', 'age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 5.3 取出索引为[3, 4, 8]行的animal和age列

In [8]:
df.loc[df.index[[3, 4, 8]], ['animal', 'age']]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 5.4. 取出age值大于3的行

In [9]:
df[df['age'] > 3]

  animal  age  visits priority
e    dog  5.0       2       no
g  snake  4.5       1       no
i    dog  7.0       2       no

### 5.5 取出age值缺失的行

In [10]:
df[df['age'].isnull()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 5.6 取出age在2,4间的行（不含）

In [11]:
df[(df['age']>2) & (df['age']>4)]
# 方法二
# df[df['age'].between(2, 4)]

  animal  age  visits priority
e    dog  5.0       2       no
g  snake  4.5       1       no
i    dog  7.0       2       no

### 5.7 f行的age改为1.5

In [12]:
df.loc['f', 'age'] = 1.5

### 5.8 计算visits的总和

In [13]:
df['visits'].sum()

19

### 5.9 计算每个不同种类animal的age的平均数

In [14]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

### 5.10 在df中插入新行k，df.loc['k'] = [5.5, 'dog', 'no', 2]，然后删除该行

In [15]:
#插入
df.loc['k'] = [5.5, 'dog', 'no', 2]
# 删除
df = df.drop('k')
df

  animal  age visits priority
a    cat  2.5      1      yes
b    cat  3.0      3      yes
c  snake  0.5      2       no
d    dog  NaN      3      yes
e    dog  5.0      2       no
f    cat  1.5      3       no
g  snake  4.5      1       no
h    cat  NaN      1      yes
i    dog  7.0      2       no
j    dog  3.0      1       no

### 5.11 计算df中每个种类animal的数量

In [16]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 5.12 先按age降序排列，后按visits升序排列

In [17]:
df.sort_values(by=['age', 'visits'], ascending=[False, True])

  animal  age visits priority
i    dog  7.0      2       no
e    dog  5.0      2       no
g  snake  4.5      1       no
j    dog  3.0      1       no
b    cat  3.0      3      yes
a    cat  2.5      1      yes
f    cat  1.5      3       no
c  snake  0.5      2       no
h    cat  NaN      1      yes
d    dog  NaN      3      yes

### 5.13. 将priority列中的yes, no替换为布尔值True, False

In [18]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})
df

  animal  age visits  priority
a    cat  2.5      1      True
b    cat  3.0      3      True
c  snake  0.5      2     False
d    dog  NaN      3      True
e    dog  5.0      2     False
f    cat  1.5      3     False
g  snake  4.5      1     False
h    cat  NaN      1      True
i    dog  7.0      2     False
j    dog  3.0      1     False

### 5.14 对每种animal的每种不同数量visits，计算平均age，即，返回一个表格，行是aniaml种类，列是visits数量，表格值是行动物种类列访客数量的平均年龄

In [19]:
df.pivot_table(index='animal', columns='visits', values='age', aggfunc='mean')

visits    1    2     3
animal
cat     2.5  NaN  2.25
dog     3.0  6.0   NaN
snake   4.5  0.5   NaN